name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # 🟢 This tells GitHub to use secrets from the 'production' environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip the application
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          zip -r app.zip . -x "*.git*" "__pycache__/*" "*.env"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: calc-api
          environment_name: calc-api-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: app.zip
