name: Run Tests in Multiple Environments

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Simulate ${{ matrix.environment }} environment
        run: |
          echo "ENV=${{ matrix.environment }}" > .env
          if [ "${{ matrix.environment }}" = "staging" ]; then
            echo "DEBUG=True" >> .env
          else
            echo "DEBUG=False" >> .env
          fi

      - name: Run tests
        run: pytest
